# Generated by Django 4.1.3 on 2023-01-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_added",
            field=models.DateField(auto_now_add=True),
        ),
    ]
