# Generated by Django 4.1.3 on 2023-01-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_api", "0003_remove_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user",
            new_name="user_type",
        ),
    ]
